console.info('checking migration status...')
await Bun.sleep(200)
console.info('applying 001_create_users... done')
await Bun.sleep(150)
console.info('applying 002_create_orders... done')
await Bun.sleep(150)
console.info('applying 003_add_indexes... done')
await Bun.sleep(100)
console.info('all migrations applied successfully')
